# Default values for deepfence.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: deepfenceio/deepfence_agent_ce
  tag: latest

managementConsoleIp: 127.0.0.1

resources:
  requests:
    cpu: 150m
    memory: 512Mi
  limits:
    memory: 1024Mi